# -*- coding: utf-8 -*-
"""customer-churn-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekCg5afft8vNZa72a4_CDqgklu5Va4do
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

"""#1. Introduction
#2. Business Problem
#3. Dataset Overview
#4. Data Cleaning
#5. Exploratory Data Analysis (EDA)
#6. Key Insights
#7. Recommendations
#8. Conclusion

# Customer Churn Analysis

This project analyzes customer churn data for a telecommunications company to identify key factors that influence customer attrition and provide data-driven retention recommendations.

## Business Problem

Customer churn is a major challenge for subscription-based businesses.  
The goal of this analysis is to understand **why customers leave** and identify patterns that can help reduce churn.
"""

# Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Load dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Display first 5 rows
df.head()

# Shape of dataset
print(df.shape)

# Column info
df.info()

# Basic stats
df.describe()

df.dtypes

#Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

#Handle missing values
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

#Encode target variable
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

#Remove unnecessary column
df = df.drop(columns=['customerID'])

#Final check
print(df.isnull().sum())
print(df.dtypes)

"""## Data Cleaning Summary

- Converted `TotalCharges` to numeric format
- Filled missing values using median
- Encoded `Churn` as binary (1 = Yes, 0 = No)
- Removed customerID column (irrelevant)

"""

#Exploratory Data Analysis (EDA)- Churn Distribution
sns.countplot(x='Churn', data=df)
plt.title("Churn Distribution")
plt.show()

#Churn by Contract Type
sns.countplot(x='Contract', hue='Churn', data=df)
plt.title("Churn by Contract Type")
plt.xticks(rotation=45)
plt.show()

"""Insight: Month-to-month contracts likely have higher churn."""

#Tenure vs Churn
sns.boxplot(x='Churn', y='tenure', data=df)
plt.title("Tenure vs Churn")
plt.show()

"""Insight: Shorter tenure → higher churn."""

#Monthly Charges vs Churn
sns.boxplot(x='Churn', y='MonthlyCharges', data=df)
plt.title("Monthly Charges vs Churn")
plt.show()

"""Insight: Higher monthly charges → higher churn probability.

## Key Insights

1. Month-to-month contract customers are more likely to churn.
2. Customers with shorter tenure are at higher risk.
3. Higher monthly charges correlate with higher churn rates.

## Recommendations

- Incentivise long-term contracts to reduce churn.
- Provide onboarding support to new customers.
- Offer discounts to high-risk, high-monthly-charge customers.

## Conclusion

By analyzing customer behavior, we identified key churn drivers. Acting on these insights can improve customer retention and increase revenue.
"""